import type { Metadata } from "next";
import * as G from "@/global";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <G.GlobalThemeProvider>
      <html lang="ko">
        <head></head>
        <G.StyledComponentsRegistryProvider>
          <body className={G.ibmPlex.variable} suppressHydrationWarning={true}>
            {children}
          </body>
        </G.StyledComponentsRegistryProvider>
      </html>
    </G.GlobalThemeProvider>
  );
}
