import type { Metadata } from "next";
import * as G from "@/global";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <G.GlobalThemeProvider>
      <G.RootStyle />
      <html lang="ko">
        <head></head>
        <body className={G.ibmPlex.variable} suppressHydrationWarning={true}>
          <G.StyledComponentsRegistry>{children}</G.StyledComponentsRegistry>
        </body>
      </html>
    </G.GlobalThemeProvider>
  );
}
