import type { Metadata } from "next";
import * as G from "@/global";
import { IBM_Plex_Sans } from "next/font/google";

const ibmPlex = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "fallback",
  style: ["normal"],
  subsets: ["latin"],
  preload: true,
  variable: "--ibm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <G.GlobalThemeProvider>
      <html lang="ko">
        <head></head>
        <G.StyledComponentsRegistryProvider>
          <body className={ibmPlex.variable} suppressHydrationWarning={true}>
            <div id="portal-for-modal" />
            {children}
          </body>
        </G.StyledComponentsRegistryProvider>
      </html>
    </G.GlobalThemeProvider>
  );
}
